// src/utils/pdfHelper.js
import { jsPDF } from "jspdf";

export const generateHandshakePDF = (loanData, user) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleDateString();

  // Header
  doc.setFontSize(20);
  doc.setTextColor(134, 25, 143); // Fuchsia color to match your theme
  doc.text("LOAN CALCULATION REPORT", 20, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${date}`, 20, 30);
  doc.line(20, 35, 190, 35);

  // Data Section
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text(`Client Name: ${user.name}`, 20, 50);
  doc.text(`Principal Amount: KSh ${Number(loanData.amount).toLocaleString()}`, 20, 60);
  doc.text(`Interest Rate: ${loanData.interest}%`, 20, 70);
  doc.text(`Loan Term: ${loanData.term} Months`, 20, 80);

  // Financial Summary
  doc.setFont("helvetica", "bold");
  doc.text(`Monthly Payment: KSh ${loanData.monthly}`, 20, 100);
  doc.text(`Total Interest: KSh ${loanData.totalInterest}`, 20, 110);
  doc.text(`Total Repayment: KSh ${loanData.totalRepayment}`, 20, 120);

  // Footer
  doc.setFont("helvetica", "italic");
  doc.setFontSize(10);
  doc.text("Generated by LoanCalc - Estimates only.", 20, 140);

  // Save the file
  doc.save(`Loan_Summary_${date}.pdf`);
};